### ISSUE TITLE
Multiple issues related to multi-level inheritance

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#226]
I've discovered a few issues that occur under very specific inheritance scenarios. I haven't been able to debug them yet, but I think I've found a way to accurately reproduce them (my tests were performed using msvc140, built in the default Debug x64 configuration, using a dynamically linked lua 5.3).

Both crashes are related to constructing inheriting bound usertypes from lua land (happens on both usertypes and simple_usertypes). I'll describe the two separate issues I discovered in comments down below to keep everything clean.

Here are my class definitions:
```cpp
class TestClass00 {
public:
	int Thing() const { return 123; }
};

class TestClass01 : public TestClass00 {
public:
	TestClass01() : a(1) {}
	TestClass01(const TestClass00& other) : a(other.Thing()) {}

	int a;
};

class TestClass02 : public TestClass01 {
public:
	TestClass02() : b(2) {}
	TestClass02(const TestClass01& other) : b(other.a) {}
	TestClass02(const TestClass00& other) : b(other.Thing()) {}

	int b;
};

class TestClass03 : public TestClass02 {
public:
	TestClass03() : c(2) {}
	TestClass03(const TestClass02& other) : c(other.b) {}
	TestClass03(const TestClass01& other) : c(other.a) {}
	TestClass03(const TestClass00& other) : c(other.Thing()) {}
	
	int c;
};
```

And the usertype definitions:
```cpp
sol::usertype<TestClass00> s_TestUsertype00(
	sol::call_constructor, sol::constructors<sol::types<>>(),
	"Thing", &TestClass00::Thing
);

lua->set_usertype("TestClass00", s_TestUsertype00);

sol::usertype<TestClass01> s_TestUsertype01(
	sol::call_constructor, sol::constructors<sol::types<>, sol::types<const TestClass00&>>(),
	sol::base_classes, sol::bases<TestClass00>(),
	"a", &TestClass01::a
);

lua->set_usertype("TestClass01", s_TestUsertype01);

sol::usertype<TestClass02> s_TestUsertype02(
	sol::call_constructor, sol::constructors<sol::types<>, sol::types<const TestClass01&>, sol::types<const TestClass00&>>(),
	sol::base_classes, sol::bases<TestClass01, TestClass00>(),
	"b", &TestClass02::b
);

lua->set_usertype("TestClass02", s_TestUsertype02);

sol::usertype<TestClass03> s_TestUsertype03(
	sol::call_constructor, sol::constructors<sol::types<>, sol::types<const TestClass02&>, sol::types<const TestClass01&>, sol::types<const TestClass00&>>(),
	sol::base_classes, sol::bases<TestClass02, TestClass01, TestClass00>(),
	"c", &TestClass03::c
);

lua->set_usertype("TestClass03", s_TestUsertype03);
```

**Comment by OrfeasZ** [comment]
Here's the code to reproduce the first crash:
```lua
local x = TestClass00()
local y = TestClass02(x)
```

And it produces the following exception (similar to #166) on line 2 of the lua script: `sol: attempt to index (get) nil value "├óΓäó┬ío├»┬╜┬í.(├ó┼ô┬┐├á┬╕┬║├»┬╜┬í ├ó┼ô┬┐├á┬╕┬║)" on userdata (bad (misspelled?) key name or does not exist)`.

I have also tried other variations of defining the usertypes, where I wouldn't define the constructors for inherited classes assuming they would be inherited from base classes, but that produced the same issue.

**Comment by OrfeasZ** [comment]
The second issue can be reproduced using the following code:
```lua
local x = TestClass01()
local y = TestClass03(x)
```

The issue occurs again on line 2, however it causes a crash, not an exception, as it seems to call the wrong constructor (`TestClass03::TestClass03(const TestClass02& other)` instead of `TestClass03::TestClass03(const TestClass01& other)`), and it also passes the `other` value as a null struct. It therefore crashes with the error `other was nullptr.`.

**Comment by OrfeasZ** [comment]
I understand that 'upcasting' classes like that can be considered bad practice, however in my use case it is necessary due to lack of a better alternative.

**Comment by ThePhD** [comment]
Well, I think I fixed it all. I think.

**Comment by OrfeasZ** [comment]
Awesome! If you commit it I can try it out on some more advanced and real-world use cases. :)

**Comment by OrfeasZ** [comment]
The first issue seems to be fixed, however I'm still experiencing the second one. Trying to figure out if there's something wrong with my environment setup and I'll report back.

With that being said, I seem to be having a new issue now which appears to occur when a usertype with a destructor is being destroyed from `sol::detail::user_alloc_destroy`. I've experienced this issue twice so far, one where the error is `__imp_lua_touserdata(...) returned nullptr.` and the other where I'm getting a reading violation in my destructor (looks like the this pointer is set to `nullptr`).

**Comment by ThePhD** [comment]
That usually indicates that I've done something wrong and there's a double delete... if you can figure it out, file a new issue. I'm gonna mark this one fixed.

https://github.com/ThePhD/sol2/releases/tag/v2.14.2

**Comment by OrfeasZ** [comment]
Okay, I'll try again with the latest version as I was using the one from [this](https://github.com/ThePhD/sol2/commit/132ff87fbcd5baa5229f285e4eabcc1b133d0609) commit. If I'm still experiencing issues I'll let you know. Again, thanks for your amazing work!
