### ISSUE TITLE
Lua error stays on stack if it happens when running sol::state::script. 

### ISSUE THREAD

**Issue by eliasdaler** [ThePhD/sol2#260]
Repro:
```cpp
#include <iostream>
#include <sol.hpp>

int main()
{
    sol::state lua;
    lua.open_libraries();
    try {
        lua.script("This_code_will_break.everything = true");
    }
    catch (const std::exception& e) {
        std::cout << e.what();
    }
    int x = lua_gettop(lua); // should be 0, but is 1!
}
```

For some reason, the error message just stays on top of the stack, but it should be removed.

**Comment by ThePhD** [comment]
Fixed in latest: https://github.com/ThePhD/sol2/commit/76cae575e8043de6d280adf09f813a56c3e16ffe

**Comment by eliasdaler** [comment]
Thanks! That fixed the problem.

For some reason, it still crashes on my release build, so I'll investigate what causes that and will post an update soon.
And be sure to check it other things use the same mechanism, because previously I had similar problems with sol::protected_function. (And I'm not sure if sol::state::script_file behaves correctly too).

**Comment by eliasdaler** [comment]
Ok, after hours of research, I've found a minimal example...
VS 2015, Update 3 RC.
It crashes only on Release build, which is default "Release" mode in VS projects. (-O2)

```cpp
#include <sol.hpp>
#include <iostream>
#include <string>

int main()
{
    sol::state lua;
    lua.open_libraries();
    try {
        lua.script("x = nil / nil"); // OK
    }
    catch (const sol::error& e) {
        std::cout << e.what() << std::endl;
    }

    std::string code = "x = nil / nil";
    try {
        lua.script(code); // CRASH HERE
    }
    catch (const sol::error& e) {
        std::cout << e.what() << std::endl;
    }
}
```

Calling lua::state::script with std::string is working correctly at first, reaching [this line](https://github.com/ThePhD/sol2/commit/76cae575e8043de6d280adf09f813a56c3e16ffe#diff-cedd1ed139bc62fa049e6365070939f4R12363) but then for some unknown reason, it goes [there](https://github.com/ThePhD/sol2/commit/76cae575e8043de6d280adf09f813a56c3e16ffe#diff-cedd1ed139bc62fa049e6365070939f4R12365) and I get an unhandled exception. Hope you're able to reproduce the problem. T_T
