### ISSUE TITLE
(lacking) type safety of T -> unique_usertype<T>

### ISSUE THREAD

**Issue by rohlem** [ThePhD/sol2#422]
(Preface: Yo. Sol2 is amazing. Many thanks.)

After some initial testing with unique_usertype types I came to the conclusion that Sol wholly equates a unique_usertype to its `::type` proxee, the type it represents.
(My best attempt at) a minimal test scenario:
```
//SOL_CHECK_ARGUMENTS isn't of any help either
#define SOL_CHECK_ARGUMENTS
#include <Sol/sol.hpp>

#include <iostream>
#include <memory>

// make a type
struct test{int special_value = 17;}; //never reset, should only ever be 17
// test function that takes a unique_ptr argument
void print_up_test(std::unique_ptr<test>& x){
	std::cout
		<< static_cast<void*>(x.get()) << " : " << std::flush
		<< x->special_value << std::endl;
}

int main(){
	// setup ...
	sol::state s;
	s.open_libraries();
	// tell Lua about the function
	s.set_function("print_up_test", &print_up_test);
	// unique_ptr object works as expected
	s["up_test"] = std::make_unique<test>();
	s.script("print_up_test(up_test)");
	// normal object is blindly accepted, leading to a bogus address with either a garbage value or triggering a segfault
	s["direct_test"] = test{};
	s.script("print_up_test(direct_test)");
}
```
Output on my setup (some mingw-w64 g++ 7.1.0):
```
0x339740 : 17
0x8800002b4f7b1624 : <program crash>
```
The same behaviour is observed when calling a functor created by sol::overload. (tested in C++17 as well as C++14 mode, just in case)

Maybe this behaviour is by design, I couldn't find exact wording regarding the type conversions in the documentation however (other than the fact that unique_ptr -> pointer works without issue), so I was quite surprised of this silent error. Specializing sol::is_unique_usertype of the specific unique_ptr specialization to std::false_type removes the implicit illegal cast, rejects the argument in the above example with SOL_CHECK_ARGUMENTS and makes use cases with sol::overload behave correctly/usefully.

Many applications will probably differentiate the usage of Lua owned objects and proxies, so it would be understandable to leave this unsupported/undefined; my original use case would have involved a bunch of custom iterators/proxies of mixed-owning nature, but making them non-unique_usertype and putting `:get()` calls in between in Lua doesn't pose a huge usability issue either. :P

**Comment by ThePhD** [comment]
Your test case would work if you took an argument of `test*`. That is, while the documentation does not say you can go from `test` -> `std::unique_ptr<test>`, `test*` -> `std::unique_ptr<test>`, `std::shared_ptr<test>` -> `std::unique_ptr<test>`... because you can't.

`std::unique_ptr` owns its own memory. Additionally, every object you push into `sol2` gives Lua the deliberate responsibility of managing its memory (unless it's a `unique_usertype`, then we turn that over to whatever destructor comes with the type). Because Lua is a language that has garbage collection and makes certain promises / guarantees about lifetime, we cannot support the kind of type conversions you're asking for without implementation-specific hacking.

As a side note: I don't know what you're trying to build, but "... mixed ownership ..." sounds like a minefield. Unless you're building something crazy, you have 2 kinds of ownership: unique, or shared. Almost every ownership pattern can be built off of those 2. Transferring ownership should be either by-copy, or by-move. Any other scheme is bound to become an absolute headache for you.

If you want to control the lifetime yourself, keep the `std::unique_ptr` around in C++ and simply had Lua raw pointers to the memory. If you do not, then create a new unique_ptr / move that unique_ptr into Lua. The system will handle the rest.

**Comment by rohlem** [comment]
I know what unique_ptr does, but thank you for the in-depth explanation ^^. Yes, my use case was kind of a minefield-esque experiment, I was trying to give a type an sol::overload member functor of unique_ptr and a stable custom container iterator (and maybe itself, as a fallback), so the code was meant to use `create(args):get().id` and `find(filter):get().id` equivalently. But no big loss.

I guess I didn't phrase my initial message correctly, I am _not_ proposing a way to turn any object into a unique_ptr reference, you're right in that would make a total mess of ownership semantics. I was rather noting the fact that Sol _currently does_  blindly convert an object of any type to a unique_ptr in a function argument (presumably via static_cast-ing its Lua-userdata void* representation). While not many sensible use cases would use this behaviour, the documentation _did_ lead me to believe that sol::overload can be used to distinguish types, which horribly fails with unique_usertypes.

As I wrote earlier, I might be misunderstanding the scope and intended use case of unique_usertype, but this type of conversion (T -> unique_usertype<T>, custom types other than std::unique_ptr<T> and std::shared_ptr<T> exhibit the same behaviour) is _utterly useless_ and can lead to errors. Removing unqiue_usertype semantics from this specialization, f.e. by

```
namespace sol{ template <> struct is_unique_usertype<std::unique_ptr<test>> : std::false_type {}; }
```

fixes the behaviour and, in my view correctly, enables sol::overload to work and errs with `SOL_CHECK_ARGUMENTS` enabled.

(I have a way of overcomplicating my point. I don't want Sol to convert T* into unique_ptr<T> when passed to functions (or presumably otherwise retrieving them from Lua). If I'm still not making sense, please tell me and I'll gladly give it another shot.)

**Comment by rohlem** [comment]
I guess a _correct_ usage example would be more convincing... I'm smart lol...

```
//SOL_CHECK_ARGUMENTS isn't of any help either
#define SOL_CHECK_ARGUMENTS
#include <Sol/sol.hpp>

#include <cstdlib>
#include <memory>

int main(){
	sol::state s;
	struct test{} t;
	s.set_function
	("distinguish",
	 sol::overload
	 ([](const std::unique_ptr<test>&){return EXIT_FAILURE;}, //failure if Sol thinks it's a unique_ptr
	  [](const test&){return EXIT_SUCCESS;})); //success if Sol thinks it's a test object
	return s["distinguish"](t); //give it a test object
}
```
Sol thinks the object is a unique_ptr, which it isn't. That's either by design (please document, but I don't understand why) or an error (I didn't yet look into where that resolution happens, but it should be manageable to allow `unique_usertype -> T` while disallowing `T -> unique_usertype`).

**Comment by ThePhD** [comment]
I actually put together an example from what you wrote earlier before you posted that, aha. I should have said something about that before finishing it so you didn't have to write an example...

Either way, this is now fixed in latest. Pull from latest to have it in there.

**Comment by rohlem** [comment]
Wow, you're fast. Confirmed working, thanks.

**Comment by rohlem** [comment]
Aaaaactually, one more thing, different unique_usertypes still get mixed up. Pls fix too (or document somewhere)?
Extended code from earlier:
```
#define SOL_CHECK_ARGUMENTS
#include <Sol/sol.hpp>
#include <cstdlib>
#include <memory>

int main(){
	sol::state s;
	struct test{};
	s.set_function
	("distinguish",
	 sol::overload
	 ([](const std::unique_ptr<test>&){return EXIT_FAILURE;}, //failure if Sol thinks it's a unique_ptr
	  [](const std::shared_ptr<test>&){return EXIT_SUCCESS;}, //success if Sol discerns it as shared_ptr
	  [](const test&){return EXIT_FAILURE;})); //failure if Sol thinks it's a test object
	return s["distinguish"](std::make_shared<test>()); //give it a test object
} //returns EXIT_FAILURE
```

**Comment by ThePhD** [comment]
This is borderline "who needs this", but at this point it's probably worth checking anyhow.

At the moment, I don't store type information with the data. The only way I can imagine making this work is by doing 1 of 2 things:

1. Store the usertype ID with the usertype itself (+4 bytes for every single userdata)
2. Add more usertype tables that track this data on a metatable level

Option 1 is precise but overt in demanding every type basically store my own version of a hacked up `std::type_info`.
Option 2 is not quite as precise but requires that I make 7-9 different tables to track usertype differences. Option 2 also has more implications (for example, right now we don't trap `const` or `volatile`  or `&&` in the Lua type system: we simply copy and then disregard, because none of those modifiers are useful in Lua and there's no effective way to mimic them without increasing the amount of tables we make).

We also incur more compile-time problems as I have to do more compile-time garbage to filter `const`/`volatile` functions and trap them to types. I'd also need to do checks to drown out differences between `shared_ptr` and `unique_ptr` when they don't matter (`test*`), and then also when they're not (`std::shared_ptr<test>`)....

... 

... I'm going to worry about this later. Please try to find your own workaround for this in the meantime. I would also suggest not trying to behave different based on ownership. In your older post, I would suggest inserting the item into the container first, then working on what's in the container to avoid having to worry about ownership. It might not be a beautiful one-liner, but it will probably get the job done.

**Comment by rohlem** [comment]
Yeah, I expected something like that... thank you for the detailed background, I'd go as far as to say it's not worth your effort lol. As you said, there are many nuances to the type system Sol currently disregards for improved interface and performance.
My original use case will probably end up not using unique_usertype at all, `proxy:get()` isn't too much of a sacrifice, probably even avoidable with some __index metatable magic.
Again, thank you for your efforts and Sol2 in the first place!
