### ISSUE TITLE
Alignment error with member callback

### ISSUE THREAD

**Issue by TheLartians** [ThePhD/sol2#514]
The following example, where we try to execute a `std::function` member object, creates alignment errors on clang 6.0.0 according to the UndefinedBehaviorSanitizer.

```
#include <sol.hpp>
#include <functional>
#include <iostream>

struct Test{
  std::function<void()> callback = [](){ std::cout << "Hello world!" << std::endl; };
};

int main() {
  sol::state lua;
  lua.new_usertype<Test>("Test","callback",&Test::callback);
  Test test;
  lua["test"] = &test;
  lua.script("test.callback()");
  return 0;
}
```

when compiled using `clang++ --std=c++14 -fsanitize=undefined ...` a cascade of 'misaligned address' runtime errors is generated, beginning with

``` 
(a.out:x86_64+0x1000d8c48): runtime error: constructor call on misaligned address 0x7fc01c405518 for type 'sol::function_detail::functor_function<std::__1::function<void ()> >', which requires 16 byte alignment
0x7fc01c405518: note: pointer points here
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^ 
```  

Otherwise the program executes as expected.

**Comment by ThePhD** [comment]
Don't use clang 6. Would have to investigate memory address issues and how to correct alignment (is it even a real problem?), but I don't know the extent of this thing's effect.

**Comment by mrgreywater** [comment]
The problem is likely due to the fact that sol uses std::allocator<T> to allocate the block of memory, and std::allocator doesn't have any alignment guarantees afaik.
https://github.com/ThePhD/sol2/blob/5816c6c34b1386c8bd852b5515199952cd51a5b8/sol/raii.hpp#L34
It would probably make sense to switch to `new`/`delete` instead, since that is supposed to allocate with the correct alignment. Alternatively maybe implement a aligned allocator, that takes std::alignment_of(T) into consideration.

**Comment by mrgreywater** [comment]
Scrap that last comment, allocation is done with lua_newuserdata, and that needs to take the alignment into consideration.
I think the only fix is to supply a custom lua_Alloc function in lua_newstate that returns aligned memory. Otherwise you would have to manually add sufficient padding after calling lua_newuserdata.

**Comment by TheLartians** [comment]
> is it even a real problem?

I haven't given data alignment much thought until now, however many sources indicate that dereferencing misaligned pointers is indeed undefined behaviour or at least a heavy performance impact. See for example this [Stackoverflow post](https://stackoverflow.com/questions/13881487/should-i-worry-about-the-alignment-during-pointer-casting) or even [Apple's developer documentation](https://developer.apple.com/documentation/code_diagnostics/undefined_behavior_sanitizer/misaligned_pointer).

Additionally, it renders clangs UndefinedBehaviorSanitizer useless as the noise created from this issue can hide other problems elsewhere in the code.

As @mrgreywater mentioned, the problem should be straightforward to solve by taking the alignment into account when allocating new objects and retrieving the pointers from lua.

**Comment by ThePhD** [comment]
Only now do I realize what "Don't use clang 6" sounds like. I meant "I don't use clang 6, so I have no idea".

I'll look into alignment-adjusting the whole framework.

**Comment by ThePhD** [comment]
So this really sucks.

`std::align` works with a current memory pointer. `lua_newuserdata` returns its own pointer, __after__ I already request a size. There's no way for me to have perfectly aligned, un-over-allocated data without allocating something with `lua_newuserdata`, and then performing `std::align` on it, because if the data is too small then it just won't fit, and if that's the case then I nede to do `lua_newuserdata` again with a larger value.

BUT, there's no guarantee that the new alignment will work inside the second `lua_newuserdata`, because it can be a COMPLETELY DIFFERENT section of memory that doesn't behave the same with respect to alignment. In other words: holy cow this SUCKS.

**Comment by TheLartians** [comment]
Unfortunately, if we have no control over where the data is allocated, we need to over-allocate to be able to always match the alignment requirement. For most data types with no strong alignment this extra space `alignof(T) - 1` should be negligible or at least very small. For users with strong memory requirements, maybe a macro such as `SOL_NO_USERDATA_ALIGNMENT` could be disable the alignment requirement. 

Unfortunately I know nothing about the inner workings of sol, but maybe this mockup code can help.

```
template <class T> T * align(void * ptr){
  size_t address = size_t(ptr);
  auto offset = address % alignof(T);
  auto aligned_address = reinterpret_cast<T*>(offset == 0 ? address : address + alignof(T) - offset);
  return reinterpret_cast<T*>(aligned_address);
}

template <class T> size_t maximum_space_needed_to_align(){
  return sizeof(T) + alignof(T) - 1;
}

template <class T,typename ... Args> void * construct_aligned(Args ... args){
  void * pointer = lua_newuserdata(maximum_space_needed_to_align<T>());
  T * aligned = align<T>(pointer);
  new (aligned) T(args...);
  return pointer;
}
```

We can now allocate a perfectly aligned `std::function` and call it. 

```
void example(){
  // f_ptr is the pointer we get from Lua
  auto f_ptr = construct_aligned<std::function<void()>>([](){ std::cout << "Hello aligned World!" << std::endl; });
  // f is the actual aligned data
  std::function<void()> &f = *align<std::function<void()>>(f_ptr);
  f(); // -> "Hello aligned World!"
}
```

**Comment by TheLartians** [comment]
Of course if caching doesn't matter, another simple possibility is to allocate and free the memory manually with `new` and `delete` (which already take care of alignment), and only store the pointer as lua userdata.

**Comment by mrgreywater** [comment]
@ThePhD It will work, i'm sure of it. Give me a day or so, i'll prepare a PR.

**Comment by TheLartians** [comment]
A quick and dirty fix of this specific issue would be to remove the 16 bit alignment dependency of `functor_function `, which is created by implicitly including a `std::function` member object. If we instead keep a pointer to the member, the above code runs fine.

	template <typename Func>
	struct functor_function {
		typedef std::decay_t<meta::unwrap_unqualified_t<Func>> function_type;
    std::unique_ptr<function_type> fx;

		template <typename... Args>
		functor_function(function_type f, Args&&... args)
    : fx(std::make_unique<function_type>(std::move(f), std::forward<Args>(args)...)) {
		}

		int call(lua_State* L) {
			return call_detail::call_wrapped<void, true, false>(L, *fx);
		}

		int operator()(lua_State* L) {
			auto f = [&](lua_State*) -> int { return this->call(L); };
			return detail::trampoline(L, f);
		}
	};

Of course, the general problem with the alignment of arbitrary user types remains. However, users may be able to work around this by providing their own factory methods that return smart pointers.

**Comment by mrgreywater** [comment]
Uh, if try to access unaligned adresses, it will crash on some platforms though, e.g all ARM before ARMv6, some PowerPC processors etc. Also SIMD instructions will fail on x86, and generally it's slower. It's just not a good idea overall.

**Comment by TheLartians** [comment]
I completely agree, the alignment issue needs to be fixed asap. This was only meant as a temporary suggestion/fix/input as this *definitely* leads to a misaligned read (without even creating a usertype in lua)  that cannot be prevented until alignment is fully fixed.

**Comment by ThePhD** [comment]
Do pointers themselves need to be aligned? 🤔

**Comment by mrgreywater** [comment]
@ThePhD malloc is guaranteed to return memory aligned for pointers. So it'll work fine as long as you don't supply a totally broken lua_Alloc.

**Comment by ThePhD** [comment]
Sounds like I need to write a test case where I supply a totally broken `lua_Alloc`, then.

**Comment by mrgreywater** [comment]
Na, then even lua_lightuserdata and the lua internals will be broken.

**Comment by ThePhD** [comment]
While we're here, bikeshedding names that turn this off. Or should it be to turn it on? It should probably be on by default, turned off explicitly. Here are some "turn me off" names we could use:

- `SOL_UNALIGN(ED)_MEMORY`
- `SOL_USE_UNALIGNED_MEMORY`
- `SOL_NO_ALIGN_MEMORY`
- `SOL_UNALIGNED_READS_IN_CURRENT_YEAR_QUESTION_MARK`

Last one may or may not be serious.

**Comment by mrgreywater** [comment]
I don't even think it needs a makro. If the user passes a type that has an alignment as requirement, it should be properly aligned. In all other cases, std::alignment_of<T>() will be '1' and then there is no memory wasted.

**Comment by TheLartians** [comment]
I have no Idea what Lua does internally, but in my tests `lua_newuserdata` always returned 8-byte aligned pointers. If this is guaranteed somewhere (probably the result is just direct output from `malloc`/`realloc` or something similar) we can even avoid over-allocation for all types where `alignof(T) <= alignof(void*)`. This is because the alignment must be a power of two. As most usertypes will probably be 8-aligned or less and there will be a good reason if they are not, I agree that we don't need a macro.
Regardless, I will go with `SOL_NO_MEMORY_ALIGNMENT`.

**Comment by mrgreywater** [comment]
The alignment of malloc is always `>= sizeof(void*)` and usually exactly that (8bytes on 64bit machines). I could change it in the PR so that it doesn't try to align in such cases, but hat just requires the same fallback alignment as I had previously afterwards, incase lua_newuserdata didn't actually return an 8 byte aligned pointer. I don't think it's worth it it.

**Comment by ThePhD** [comment]
Pull the latest and try it, your members should be aligned, even with a misbehaving allocator.

Thanks for reporting this issue.

**Comment by TheLartians** [comment]
Unfortunately, I cannot confirm that the issue is fixed. The alignment errors persist and the program segfaults. Using the latest commit and the code above I the first alignment issue I get is

```
sol.hpp:8326:11: runtime error: reference binding to misaligned address 0x7f92fe404f58 for type 'std::remove_reference_t<functor_function<function<void ()> > >' (aka 'sol::function_detail::functor_function<std::__1::function<void ()> >'), which requires 16 byte alignment
0x7f92fe404f58: note: pointer points here
 00 00 00 00  00 00 00 00 00 00 00 00  c0 85 97 05 01 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^ 
```
which corresponds to the following line in the `getter<user<T>>` method.

```
return *static_cast<std::remove_reference_t<T>*>(lua_touserdata(L, index));
```

As the memory created by the 'dumb pusher' is aligned now, I think that we also need to re-allign the memory returned by `lua_touserdata`.

Sure enough, [when I naively fix the getter](https://github.com/TheLartians/sol2/commit/8efa4f615903c4cb73d21188e863c0755d1d112a), the sanitiser reported no issues and the code above runs fine. Running the included `tests` target however shows a ton of alignment errors related to `usertype_metatable` and segfaults at the end (before and after applying my fix).

**Comment by mrgreywater** [comment]
I'll be honest, but I feel like the commit that fixes the issue needs a review. It looks overly complicated and obscure in what it wants to accomplish. If you want to align the pointers aswell, just put it all in a inline struct, and let the compiler work it's magic.

e.g
```
struct userdata_t {
T* obj;
T val;
};
auto data = lua_newuserdata(L, sizeof(userdata_t) + alignof(userdata_t) - 1);
data = align(data, alignof(data))
auto user = (T)userdata_t*
user->obj = &user->val;
```

**Comment by ThePhD** [comment]
The usertype metatables are being run through the same alignment code, so it's odd that they're being reported as mis-aligned...

I fixed the getter: my apologies, I had overlooked that one. I'm going to need you to pull from the latest and give me a good sample of the sanitize errors you get, so I can check them against the implementation again.

**Comment by TheLartians** [comment]
So with the latest pull the code above runs Fien with no issues. Still crashes when running the last target though (also I had to add `#include <set>` to `test_gc.cpp` to compile). I dumped the full output from the debugger with sanitiser enabled into [this pastebin](https://pastebin.ca/3882014).
The program then exits with a EXC_BAD_ACCESS (code=EXC_I386_GPFLT). Stack trace is [here](https://pastebin.ca/3882017).
Don't think I mentioned my Setup yet for reproducability: 2017 MacBook Pro on OSX 10.12.6 and Xcode 9 (they include special version of clang, but the sanitiser output should be reproducible on any system with clang 6.0.0).

**Comment by TheLartians** [comment]
[A quick google of the error code](https://stackoverflow.com/questions/19651788/whats-the-meaning-of-exception-code-exc-i386-gpflt) found this possible cause

> Another likely causes is unaligned access with an SSE register - in other word, reading a 16-byte SSE register from an address that isn't 16-byte aligned.

From which I assume that the crash is actually linked to the previous alignment errors.

**Comment by ThePhD** [comment]
This is odd. It's calling out `light<T>` and its data-getting operations. This doesn't make any sense, because all we do is store a pointer using `lua_pushlightuserdata`, which only accepts a `void*` pointer. This would mean that Lua's allocator is screwing up on the inside....???

Or we're putting that light userdata reference in bad somewhere from a real userdata reference. Time to go digging...

**Comment by ThePhD** [comment]
Stepping through the code reveals that on my architecture `std::alignment_of<T>`, where `T` is the metatable implementation, says 8. For your platform, it's saying 16: I need someone with a step-through debugger to add a breakpoint here: 

https://github.com/ThePhD/sol2/blob/develop/sol/stack_core.hpp#L370

Then, I need them to step into the `align` function and tell me what the `std::size_t alignment` parameter's value is. As of right now, my implementation correctly aligns the metatable's stuff to the 8 byte boundary.

**Comment by TheLartians** [comment]
As you weren't clear for which specific type you needed the alignment, I added 
```
std::cout << "std::alignment_of<" << detail::demangle<T>() << ">::value = " << std::alignment_of<T>::value << std::endl;
```
right before said line. Until the crash only four distinct types had alignment other than 8:
```
std::alignment_of<sol::function_detail::functor_function<std::__1::function<int ()> >>::value = 16
std::alignment_of<sol::function_detail::functor_function<std::__1::function<void ()> >>::value = 16
std::alignment_of<sol::function_detail::functor_function<std::__1::function<unsigned long ()> >>::value = 16
std::alignment_of<sol::usertype_metatable<test_t, std::__1::integer_sequence<unsigned long, 0, 1, 2, 3>, char const (&)[2], std::__1::function<unsigned long ()>, char const (&)[2], sol::property_wrapper<double (*)(), void (*)(int)>, char const (&)[4], sol::constructor_list<sol::types<> > &, char const (&)[5], const sol::destructor_wrapper<void> &>>::value = 16
```
The last line is also the last output before the crash.

**Comment by ThePhD** [comment]
I did a test and forced the alignment value to be 16, then 32, then 64. All of those values get properly padded and fit into memory when I run through the code. I don't know what to tell you here: as far as I can tell I'm forcing alignment and doing everything right. Modulus on the addresses of the adjusted pointers returns 0, every time.

Do you have an older clang version? 6.0.0 is still an in-progress product, and I don't trust clang's tuple implementation for even half a second: does this still explode on 5.x ?

**Comment by ThePhD** [comment]
As a side note, before the "adjusted" return, try putting a print out that prints the address, and then the modulus of `static_cast<std::uintptr_t>(address) % std::alignment<T>::value`, and see what that puts out for you. If it looks weird then we know it's a sol2 problem: if not, then clang's doing something dumb.

**Comment by TheLartians** [comment]
So `size_t(adjusted) % std::alignment_of<T>::value` is always zero, as it should be. I did't inspect the pointer addresses closer. I will check out the fishy clang behaviour later when I have some spare time (and see what compiling with version 5.x does).
If it is actually a clang bug this will hopefully be addressed soon as clang 6.0.0 is the new default compiler for Mac and iOS (its bundled with the standard IDE Xcode 9).

**Comment by ThePhD** [comment]
Ooh, I think I found it. There was a disconnect between how I stored the usertype table `user<T>`, wherein I used the proper alignment, and how I retrieved it just after storing it `light<T>`. It worked before because before alignment, `light<T>` == `user<T>` in terms of memory addressing. Alignment changed that.

Try the latest.

**Comment by TheLartians** [comment]
```
Assertion failed: (!"initialized()"), function operator(), file /Users/lars/Documents/Development/sol2-thephd/sol/optional_implementation.hpp, line 602.
```
Sanitiser output looks good though.

**Comment by ThePhD** [comment]
Well, one problem down. No idea why that optional issue is firing, though, I'll have to check through it all later...

**Comment by ThePhD** [comment]
If you can give me some sample code that triggers that assertion failure, I can get to looking into it.

**Comment by TheLartians** [comment]
So as I said, the failure occurs when running the test target of the sol library (target created with CMake).  The line that crashes is line 558 in `tests.cpp`.

```
TEST_CASE("proxy/equality", "check to make sure equality tests work") {
	sol::state lua;
	REQUIRE((lua["a"] == sol::lua_nil));
	REQUIRE_FALSE((lua["a"] == nullptr)); // Boom!
	REQUIRE_FALSE((lua["a"] == 0));
	REQUIRE_FALSE((lua["a"] == 2));

	lua["a"] = 2;

	REQUIRE_FALSE((lua["a"] == sol::lua_nil)); //0
	REQUIRE_FALSE((lua["a"] == nullptr));  //0
	REQUIRE_FALSE((lua["a"] == 0));	   //0
	REQUIRE((lua["a"] == 2));		    //1
}
```

Backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fffc0aadd42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x0000000114bcf7a0 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fffc0a13420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffc09da893 libsystem_c.dylib`__assert_rtn + 320
  * frame #4: 0x000000010d7c1bb0 tests`sol::optional<std::nullptr_t>::operator*(this=0x0000000118697aa0) const &::'lambda'()::operator()() const at sol.hpp:3498
    frame #5: 0x000000010d7c1905 tests`sol::optional<std::nullptr_t>::operator*(this=0x00000001186978e0) const & at sol.hpp:3498
    frame #6: 0x000000010d7c15ce tests`bool sol::operator==<std::nullptr_t>(x=0x00000001186978e0, v=0x00007fff5fbfcc80) at sol.hpp:3818
    frame #7: 0x000000010d7c00ea tests`bool sol::operator==<sol::basic_table_core<true, sol::basic_reference<false> >&, char const (&) [2], std::nullptr_t>(right=0x00007fff5fbfcc60, left=0x00007fff5fbfcc80) [2]> const&, std::nullptr_t&&) at sol.hpp:13512
    frame #8: 0x000000010caaf70d tests`____C_A_T_C_H____T_E_S_T____45() at tests.cpp:558
    frame #9: 0x000000010c9c8115 tests`Catch::TestInvokerAsFunction::invoke(this=0x000060200000a7b0) const at catch.hpp:8848
    frame #10: 0x000000010c92e871 tests`Catch::TestCase::invoke(this=0x000062e000016180) const at catch.hpp:8749
    frame #11: 0x000000010c92e4ba tests`Catch::RunContext::invokeActiveTestCase(this=0x0000000118b89130) at catch.hpp:7791
    frame #12: 0x000000010c90e14f tests`Catch::RunContext::runCurrentTest(this=0x0000000118b89130, redirectedCout="", redirectedCerr="") at catch.hpp:7763
    frame #13: 0x000000010c900e49 tests`Catch::RunContext::runTest(this=0x0000000118b89130, testCase=0x000062e000016180) at catch.hpp:7558
    frame #14: 0x000000010c94b8e7 tests`(anonymous namespace)::runTests(config=std::__1::shared_ptr<Catch::Config>::element_type @ 0x0000611000009b58 strong=4 weak=1) at catch.hpp:7998
    frame #15: 0x000000010c940468 tests`Catch::Session::runInternal(this=0x00000001189cb020) at catch.hpp:8172
    frame #16: 0x000000010c93f1fc tests`Catch::Session::run(this=0x00000001189cb020) at catch.hpp:8132
    frame #17: 0x000000010c93ec0f tests`Catch::Session::run(this=0x00000001189cb020, argc=1, argv=0x00007fff5fbff750) at catch.hpp:8100
    frame #18: 0x000000010ca75a30 tests`main(argc=1, argv=0x00007fff5fbff750) at catch.hpp:11508
    frame #19: 0x00007fffc097f235 libdyld.dylib`start + 1
```

When the macro `NDEBUG` is defined the assertion is removed and everything seems to run fine. Including alignment :) . So maybe the check was unnecessary.

**Comment by TheLartians** [comment]
Anyways, it appears to me that the actual alignment issues are finally fixed! 
Thanks for the quick response guys!

**Comment by ThePhD** [comment]
Oh. We don't actually run the test suite with CMakeLists, but I'm actually really glad somebody used it and it almost worked, since I am going to be making our tests run by generating that and running it at some point!

You're welcome.

**Comment by dio** [comment]
> Of course, the general problem with the alignment of arbitrary user types remains. However, users may be able to work around this by providing their own factory methods that return smart pointers.

@TheLartians I'm interested this in general. Could you give an example of this? Thanks!

**Comment by ThePhD** [comment]
@dio Use `sol::factories` when you register usertypes to provide arbitrary functions that return arbitrary things. See the documentation for details: https://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-constructor-options

**Comment by TheLartians** [comment]
@dio In my case I defined call constructors to return shared pointers of my class instead of the direct instance. The class definitions look something like
```
lua.new_usertype<T>("T", 
  sol::call_constructor, sol::factories([](){ return std::make_shared<T>(); }, ...),
  ...
);
```
sol understands smart pointers, so you can still work with `T` instances instead of `std::shared_ptr<T>` wherever you need.

**Comment by dio** [comment]
Yeah, I hope I use sol. I'm trying to make sense of your code on how to allocate mem through `lua_newuserdata` and aligns it. I'm trying to fix this envoy bug: https://github.com/envoyproxy/envoy/issues/5551 Thanks!
