### ISSUE TITLE
issue when SOL_CXX17_FEATURES and SOL_USE_BOOST are declared

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#599]
When both of those define are declared, there is a mismatch with hashing function.
`typedef std::hash<std::string_view> string_view_hash;`
but
`template <typename K, typename V, typename H = boost::hash<K>, typename E = std::equal_to<>>`

One fix would be to do that
```
#ifdef SOL_USE_BOOST
#ifdef SOL_CXX17_FEATURES
		template <typename K, typename V, typename H = std::hash<K>, typename E = std::equal_to<>>
#else
    template <typename K, typename V, typename H = boost::hash<K>, typename E = std::equal_to<>>
#endif
		using map_t = boost::unordered_map<K, V, H, E>;
#else
		template <typename K, typename V, typename H = std::hash<K>, typename E = std::equal_to<>>
		using map_t = std::unordered_map<K, V, H, E>;
#endif // Boost map target
```

Thanks !

**Comment by ThePhD** [comment]
I've implemented it like this:

````
#if defined(SOL_USE_BOOST) && !defined(SOL_CXX17_FEATURES)
		template <typename K, typename V, typename H = boost::hash<K>, typename E = std::equal_to<>>
		using map_t = boost::unordered_map<K, V, H, E>;
#else
		template <typename K, typename V, typename H = std::hash<K>, typename E = std::equal_to<>>
		using map_t = std::unordered_map<K, V, H, E>;
#endif // Boost map target
````

Thanks for the catch.

**Comment by otristan** [comment]
You still want to keep  boost::unordered_map in order to keep compatible key/hash for non allocation purpose, so you still have an issue with this implementation.

**Comment by ThePhD** [comment]
Ah, you're right. Sorry, it's fixed!
