### ISSUE TITLE
Adding a non-member const rvalue to usertype

### ISSUE THREAD

**Issue by trexxet** [ThePhD/sol2#961]
I'm trying to create a usertype from `class Foo` and add some constants to it which are not presented in `Foo` - they exist in a global enum. So, consider the following:
```c++
enum { bar; } // declared somewhere outside and better stay there
class Foo {
  LuaFile* LF;
  Foo(LuaFile* LF) : LF(LF) {
    auto bind = LF->state.new_usertype<Foo> ("__Foo");
    bind["bar"] = bar;
  }
};
```
Whoops:
```
sol.hpp:16385:12: error: no type named 'function_pointer_type' in 'using traits_type = sol::wrapper<<unnamed enum>, void>::traits_type' {aka 'struct sol::lua_bind_traits<<unnamed enum> >'}
16385 |      using fp_t = typename traits_type::function_pointer_type;
```
```c++
bind["bar"] = static_cast<const int>(bar); // same shit for sol::lua_bind_traits<int>  
```
```c++
auto bind = LF->state.new_usertype<Foo> ("__Foo", "bar", bar); // same
```
That worked nice with tables, but now I have to make `Foo` a class as I need to create a buffer in LF. 
I suppose that usertype binding works only for class members, so, are there any possible workarounds?

**Comment by ThePhD** [comment]
This should be working.... you're using latest, right?

**Comment by trexxet** [comment]
Hm, updated to latest, issue remains (the line is 16283 now)
![image](https://user-images.githubusercontent.com/4649497/79864764-adcd9380-83e2-11ea-809c-3a39dfe9c1ef.png)
![image](https://user-images.githubusercontent.com/4649497/79864794-baea8280-83e2-11ea-8402-036e0fac3e8f.png)

**Comment by trexxet** [comment]
As I understand, something fails in `usertype_storage_base::set`. It goes to `(meta::is_string_like_or_constructible<KeyU>::value || std::is_same_v<KeyU, meta_function>)` branch, then 
```c++
std::string s = u_detail::make_string(std::forward<Key>(key));
bool is_index = (s == to_string(meta_function::index)); // false
```
and it runs
```c++
ics.index = is_index || is_static_index ? &Binding::template call_with_<true, is_var_bind::value>
```
so int or enum is treated as callable. 

_pls do something with it i'm too dumb to fix it myself_

**Comment by ThePhD** [comment]
Oh, duh. Sorry, this is something you need to mark explicitly when binding usertypes: you need to give it a wrapper that says "this is a normal value and not a function / variable": the wrapper for this is called `sol::var`.

Docs here:
https://sol2.readthedocs.io/en/latest/api/var.html

And also, here (See the `sol::var` option in the list):
https://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-regular-function-options


Sorry! I should have realized that sooner.
